### PR TITLE
Add article Node.js For Beginners. Deploy Your Blog to Heroku

### PR DESCRIPTION
**Pull request by lidmx**

### CODE REVIEW

**Comment by creationix** [comment]
Overall this is good, deploying to Heroku is a great place for beginners to start with.

Can you pull out the code snippets into their own files?  Also I'm not sure how comfortable I am with having "bloody" in one of the title since many consider it an explicative in British english.

**Comment by lidmx** [comment]
Good, I've added necessary files and changed the title.

**Comment by lidmx** [comment]
Is everything ok now?

**Comment by creationix** [comment]
Sorry, I got busy.

When I said to pull out the snippets into their own files, I meant the ones inlined in the markdown.  Unless it's a really small snippet (like a couple bash commands), I prefer code to not be in the markdown.  You can link to it using snippets like `<object-graphs/objects.js>`.

Also, sorry for being particular about language and style, but so many people get confused and attribute articles to me when they are clearly labeled as written by someone else.

Also code snippets should use 2-space indent to fit better in the screen with less horizontal scrolling and to match the rest of the site.

This is a rather long and well written howto, but I do have to ask.  Why do you want to publish it here instead of somewhere else?  Most the articles on this site are quite old and outdated.

**Comment by lidmx** [comment]
Got it. I moved biggest code snippets to separate files, although I left smaller code samples (1-5 lines) to be inline. Code formatting should be corrected as well.
Why publish here? I liked the articles on your site and decided to add mine. Actually, I thought about submitting my article to several resources.

**Comment by creationix** [comment]
Much better.

**Comment by creationix** [comment]
It's live! http://howtonode.org/deploy-blog-to-heroku
Do you have a twitter account so I can give you credit there too?

**Comment by lidmx** [comment]
Great, thank you. No, I don't have a twitter account. Maybe will get one later.

**Pull request merged**
