### PR TITLE
CloudBoost CloudObjects Article Added

### PR DESCRIPTION
**Pull request by nawazdhandala**

### CODE REVIEW

**Comment by nawazdhandala** [comment]
Any updates on this?

**Comment by creationix** [comment]
Sorry, I forgot about this one.

The article looks good, but I generally try to shy away from articles showing how to use libraries for commercial offerings.  

What is the purpose of publishing it here instead of on the cloudboost website or blog?

**Comment by nawazdhandala** [comment]
Hey @creationix, Yes, we have a commercial and hosted offering which is completely managed for you but we're 100% open source under Apache 2 License (this is not managed ofcourse). You can check the open source project available on Docker here : https://github.com/cloudboost/cloudboost.

**Comment by creationix** [comment]
That's awesome.  I'm not against commercial offerings, just curious why you want to publish here rather than on your own platform. 

I've had a lot of submissions in the past where people try to repost content already published on their main site for no reason other than to ride on the high-level of organic SEO that howtonode.org has.

Forgive me for trying to be more careful in checking.  I just want to know the motivation for posting here.  Like I said, the content looks great and I'm sorry I forgot about the initial submission.

**Comment by nawazdhandala** [comment]
I completely understand Tim. I thin honestly, We need to reach out to community which howtonode has built, and that's the reason why we really want to get the content up here instead of our website / blog.

**Comment by creationix** [comment]
Sounds good.  Shall I publish it now, or would you like to update the publish date in the article first?

**Comment by nawazdhandala** [comment]
Thank you so much for that Tim. You can publish it. That's okay.

**Comment by nawazdhandala** [comment]
Thank you so much @creationix for this. :)

**Comment by creationix** [comment]
hmm, it's not publishing.  Upon looking closer at the PR, it looks like your markdown file is in the root instead of in the articles directory.  Could you fix this and test locally to make sure it works?

**Comment by nawazdhandala** [comment]
I'm sorry about this. I've created a new PR.

**Pull request merged**
